name: Deploy on GH Pages

on:
    push:
        branches: [cicd]
    pull_request:
        types: [closed] # only closed PR get through
        branches: [main]

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2

    build:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - name: Install dependencies
              run: yarn
            - name: Build project
              run: yarn build

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: gh-pages
                  FOLDER: build
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
