name: Linter and build checker

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v2

            - name: Install dependencies
              run: yarn

            - name: Lint project
              run: yarn lint

            - name: Build project
              run: yarn build

            - name: Deploy
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: gh-pages
                  FOLDER: build
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
